name: CI

on:
  push:
    branches: [main, dev]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - freebsd_version: "15.0"
    name: FreeBSD ${{ matrix.freebsd_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Start FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.freebsd_version }}
          usesh: true
      - name: Setup Environment
        shell: freebsd {0}
        run: |
          pkg install rust
          . "$HOME/.cargo/env"
      - name: Build Website
        shell: freebsd {0}
        run: |
          . "$HOME/.cargo/env"
          cargo build --verbose
      - name: Run Clippy
        shell: freebsd {0}
        run: |
          . "$HOME/.cargo/env"
          cargo clippy --verbose
